version: "3"

services:
   client:
     container_name: client
     image: nginx:latest
     volumes:
       - ./client:/usr/share/nginx/html
     ports:
       - "8080:80"

   server:
     container_name: server
     build: ./server
     ports:
       - "3000:5000"

   postgres-ai-chatbot:
     container_name: postgres-ai-chatbot
     image: postgres:latest
     environment:
       POSTGRES_PASSWORD: "test"
       POSTGRES_USER: "admin1"
     ports:
       - "5432:5432"
     volumes:
       - db-data:/etc/data

volumes:
  db-data:
